<div style="float: block; text-align: center; line-height: 1.7em">
    <span style="font-size: 2em; font-weight: bold"> Fatigue-Sleepiness in Irregular Workloads for Pilots </span><br>
    <span style="font-size: 1.5em; font-weight: bold"> Statistical Modelling - Perceived Excessive Sleepiness </span><br>
</div>

----

---

# 1. Loading Libraries and Packages

In [1]:
import os                                            # system library
import pandas as pd                                  # library to handle databases
import numpy as np                                   # library to handle arrays and matrices
import matplotlib.pyplot as plt                      # graphical package
import seaborn as sns                                # beautification graphical package
from IPython.display import display, HTML

os.environ['R_HOME'] = "C:/PROGRA~1/R/R-44~1.2"      # Necessary to configure R_HOME path

import rpy2.robjects as ro                           # Forcing to UTF-8 locale
ro.r('Sys.setlocale("LC_ALL", "English_United States.UTF-8")')

from pymer4.models import Lmer                       # Package for statistical modelling

----

# 2. Reading Pre-Processed Data

In [3]:
file = os.path.join('data','slp_wrk_mdl_train.csv')
try:
    df = pd.read_csv(file)
    print('-----------------------------------------------')
    print(f"\033[93mSuccess Data file read!\033[0m")
    print('-----------------------------------------------')
    display(df.head(3))
except Exception as e:
    print('-----------------------------------------------')
    print(f"\033[91mAn error occurred:\033[0m {e}")
    print('-----------------------------------------------')

-----------------------------------------------
Success Data file read!
-----------------------------------------------

,Id,TPFS_slp,duty_moment,DMod_slp,sleep_dev,Sleep_quality,time_awake,sleep_duration,age,kssd
0,P01,base,start,base,0,5,8.466667,8.383333,base,0
1,P01,em+eve,middle,base,0,5,8.466667,8.383333,base,0
2,P01,NI,end,base,0,5,8.466667,8.383333,base,1

----

# 3. Verifying for Null rows

In [4]:
df['Sleep_quality'] = pd.to_numeric(df['Sleep_quality'], errors = 'coerce')
wsm = df.isna().sum()
display(pd.DataFrame(wsm).T)

,Id,TPFS_slp,duty_moment,DMod_slp,sleep_dev,Sleep_quality,time_awake,sleep_duration,age,kssd
0,0,0,0,0,0,29,7,3,0,0

* As we can see above for covariates time_awake and sleep duration there are some null rows, so these rows containing null values will be taken away.

In [5]:
df = df.dropna()

wsm = df.isna().sum()
display(pd.DataFrame(wsm).T)

,Id,TPFS_slp,duty_moment,DMod_slp,sleep_dev,Sleep_quality,time_awake,sleep_duration,age,kssd
0,0,0,0,0,0,0,0,0,0,0

* Now as we can see, there is no longer null rows!

In [7]:
print(df.nunique())

Id                 48
TPFS_slp            3
duty_moment         3
DMod_slp            2
sleep_dev           2
Sleep_quality       9
time_awake        265
sleep_duration    250
age                 2
kssd                2
dtype: int64

---

# 4. Scalling some covariates

To avoid scalling bias in the model, we will rescalling some continuous covariates.

In [8]:
df[['Sleep_quality','time_awake','sleep_duration']].describe().T

,count,mean,std,min,25%,50%,75%,max
Sleep_quality,1046.0,7.293499,1.723159,2.000000,6.000000,7.500000,9.000000,10.000000
time_awake,1046.0,3.923470,3.592872,0.250000,1.500000,2.391667,5.150000,17.400000
sleep_duration,1046.0,7.183748,1.780239,2.466667,6.166667,7.200000,8.383333,12.416667

Above is shown some descriptive statistics of the ordinal and continuous covariates, based on the covariate statistics we propose the max-min standardization.

In [9]:
df['Sleep_quality'] = df['Sleep_quality']/(df['Sleep_quality'].max()-df['Sleep_quality'].min())
df['time_awake'] = df['time_awake']/(df['time_awake'].max()-df['time_awake'].min())
df['sleep_duration'] = df['sleep_duration']/(df['sleep_duration'].max()-df['sleep_duration'].min())

---

# 5. Preliminary Regression Analysis

Once we have a repeated measure design, we choose a mixed logistic model given by:

<p style="text-align: center;"> $g(x_{ij},\beta_{0i},\beta_1, \beta_s) = \beta_{0i}+\beta_{1i}x_1 + x_{ij}^T\beta_s$  (level 1) </p>
<p style="text-align: center;"> $\beta_{0i} = \beta_0 + \alpha_i$  (level 1, random intercept) </p>

where $\alpha_i \sim N(0,\sigma_\alpha^2)$ .

with $\alpha_i$ representing the random intercept due to participant variability and $\beta_0$ the intercept or baselines.

The logistic link function os given by:

<p style="text-align: center;"> $$g(x_{ij},\beta_{0i},\beta_1, \beta_s) = ln\left[\frac{\pi(x_{ij},\beta_{0i},\beta_1, \beta_s)}{1-\pi(x_{ij},\beta_{0i},\beta_1, \beta_s)}\right]$$ </p>

with, 

<p style="text-align: center;"> $$\pi(x_{ij},\beta_{0i},\beta_1, \beta_s) = \frac{e^{\beta_{0i}+\beta_{1i}x_1 + x_{ij}^T\beta_s}}{1+e^{\beta_{0i}+\beta_{1i}x_1 + x_{ij}^T\beta_s}}$$</p>

## 5.1. Function to codify the covariates in pymer standards

In [10]:
def get_formula(covariates, target, prnt = False):
    formula = f'{target}~'
    for cvt in covariates:
        formula += cvt+'+'
    formula = formula[:-1]
    if prnt:
        print(f'formula:\n{formula}')
    return formula

## 5.2. First Iteration

In [11]:
covariates = ['TPFS_slp','duty_moment','DMod_slp','sleep_dev','Sleep_quality','time_awake','sleep_duration','age']

formula = get_formula(covariates, 'kssd', prnt=False)
ff = formula + '+(1|Id)'

print('----------------------------------------------------------------------------------------------------------')
print(f'\033[91mFormula: {ff}\033[0m')
print('----------------------------------------------------------------------------------------------------------')


model_LME = Lmer(ff, data = df, family = 'binomial')
mdf = model_LME.fit()

print(mdf)

----------------------------------------------------------------------------------------------------------
Formula: kssd~TPFS_slp+duty_moment+DMod_slp+sleep_dev+Sleep_quality+time_awake+sleep_duration+age+(1|Id)
----------------------------------------------------------------------------------------------------------
Model failed to converge with max|grad| = 0.00818334 (tol = 0.002, component 1)

Linear mixed model fit by maximum likelihood  ['lmerMod']
Formula: kssd~TPFS_slp+duty_moment+DMod_slp+sleep_dev+Sleep_quality+time_awake+sleep_duration+age+(1|Id)

Family: binomial	 Inference: parametric

Number of observations: 1046	 Groups: {'Id': 48.0}

Log-likelihood: -381.428 	 AIC: 786.857

Random effects:

           Name    Var    Std
Id  (Intercept)  0.453  0.673

No random effect correlations specified

Fixed effects:

                   Estimate  2.5_ci  97.5_ci     SE     OR  OR_2.5_ci  \
(Intercept)           0.947  -0.371    2.265  0.672  2.578      0.690
TPFS_slpem+eve        1.088   0.620    1.555  0.239  2.967      1.859
TPFS_slpNI            1.478   0.875    2.080  0.307  4.383      2.399
duty_momentmiddle    -1.486  -1.947   -1.026  0.235  0.226      0.143
duty_momentstart     -2.594  -3.136   -2.053  0.276  0.075      0.043
DMod_slpni            0.648   0.216    1.079  0.220  1.911      1.241
sleep_dev             0.220  -0.323    0.764  0.277  1.247      0.724
Sleep_quality        -2.498  -3.514   -1.483  0.518  0.082      0.030
time_awake            0.763  -0.241    1.768  0.513  2.145      0.785
sleep_duration       -1.231  -2.581    0.119  0.689  0.292      0.076
agemiddle             0.690   0.097    1.283  0.303  1.994      1.102

                   OR_97.5_ci   Prob  Prob_2.5_ci  Prob_97.5_ci  Z-stat  \
(Intercept)             9.629  0.721        0.408         0.906   1.408
TPFS_slpem+eve          4.737  0.748        0.650         0.826   4.558
TPFS_slpNI              8.006  0.814        0.706         0.889   4.807
duty_momentmiddle       0.358  0.184        0.125         0.264  -6.328
duty_momentstart        0.128  0.070        0.042         0.114  -9.394
DMod_slpni              2.942  0.656        0.554         0.746   2.942
sleep_dev               2.147  0.555        0.420         0.682   0.795
Sleep_quality           0.227  0.076        0.029         0.185  -4.821
time_awake              5.858  0.682        0.440         0.854   1.489
sleep_duration          1.126  0.226        0.070         0.530  -1.788
agemiddle               3.608  0.666        0.524         0.783   2.280

                   P-val  Sig
(Intercept)        0.159
TPFS_slpem+eve     0.000  ***
TPFS_slpNI         0.000  ***
duty_momentmiddle  0.000  ***
duty_momentstart   0.000  ***
DMod_slpni         0.003   **
sleep_dev          0.427
Sleep_quality      0.000  ***
time_awake         0.137
sleep_duration     0.074    .
agemiddle          0.023    *

C:\Users\jlpsc\anaconda3\envs\pymer4_projects\lib\site-packages\pymer4\models\Lmer.py:733: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  ran_vars = ran_vars.applymap(

## 5.3. Second Iteration

In [14]:
covariates = ['TPFS_slp','duty_moment','DMod_slp','Sleep_quality','sleep_duration','age']

formula = get_formula(covariates, 'kssd', prnt=False)
ff = formula + '+(1|Id)'

print('----------------------------------------------------------------------------------------------------------')
print(f'\033[91mFormula: {ff}\033[0m')
print('----------------------------------------------------------------------------------------------------------')


model_LME = Lmer(ff, data = df, family = 'binomial')
mdf = model_LME.fit()

print(mdf)

----------------------------------------------------------------------------------------------------------
Formula: kssd~TPFS_slp+duty_moment+DMod_slp+Sleep_quality+sleep_duration+age+(1|Id)
----------------------------------------------------------------------------------------------------------
Linear mixed model fit by maximum likelihood  ['lmerMod']
Formula: kssd~TPFS_slp+duty_moment+DMod_slp+Sleep_quality+sleep_duration+age+(1|Id)

Family: binomial	 Inference: parametric

Number of observations: 1046	 Groups: {'Id': 48.0}

Log-likelihood: -382.747 	 AIC: 785.494

Random effects:

           Name    Var    Std
Id  (Intercept)  0.413  0.642

No random effect correlations specified

Fixed effects:

                   Estimate  2.5_ci  97.5_ci     SE     OR  OR_2.5_ci  \
(Intercept)           1.224   0.179    2.268  0.533  3.400      1.196
TPFS_slpem+eve        1.181   0.728    1.633  0.231  3.256      2.072
TPFS_slpNI            1.627   1.057    2.196  0.291  5.087      2.878
duty_momentmiddle    -1.475  -1.934   -1.017  0.234  0.229      0.145
duty_momentstart     -2.639  -3.181   -2.098  0.276  0.071      0.042
DMod_slpni            0.727   0.307    1.147  0.214  2.069      1.360
Sleep_quality        -2.491  -3.499   -1.482  0.515  0.083      0.030
sleep_duration       -1.259  -2.477   -0.041  0.621  0.284      0.084
agemiddle             0.712   0.135    1.290  0.295  2.039      1.144

                   OR_97.5_ci   Prob  Prob_2.5_ci  Prob_97.5_ci  Z-stat  \
(Intercept)             9.664  0.773        0.545         0.906   2.296
TPFS_slpem+eve          5.119  0.765        0.674         0.837   5.116
TPFS_slpNI              8.990  0.836        0.742         0.900   5.598
duty_momentmiddle       0.362  0.186        0.126         0.266  -6.309
duty_momentstart        0.123  0.067        0.040         0.109  -9.554
DMod_slpni              3.148  0.674        0.576         0.759   3.396
Sleep_quality           0.227  0.077        0.029         0.185  -4.840
sleep_duration          0.960  0.221        0.078         0.490  -2.026
agemiddle               3.633  0.671        0.534         0.784   2.417

                   P-val  Sig
(Intercept)        0.022    *
TPFS_slpem+eve     0.000  ***
TPFS_slpNI         0.000  ***
duty_momentmiddle  0.000  ***
duty_momentstart   0.000  ***
DMod_slpni         0.001  ***
Sleep_quality      0.000  ***
sleep_duration     0.043    *
agemiddle          0.016    *

C:\Users\jlpsc\anaconda3\envs\pymer4_projects\lib\site-packages\pymer4\models\Lmer.py:733: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  ran_vars = ran_vars.applymap(